### Testando rota GET
GET http://localhost:3000/produtos
### Testando rota POST
POST http://localhost:3000/produtos
Content-Type: application/json

{
 "nome": "Notebook",
 "preco": 3500
}
### Testando rota PUT
PUT http://localhost:3000/produtos/1
Content-Type: application/json

{
 "nome": "Notebook Gamer",
 "preco": 5000
}
### Testando rota DELETE
DELETE http://localhost:3000/produtos/1